<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tn ti khon_mantine-3ftbk89k9</name>
   <tag></tag>
   <elementGuidId>d546e131-2c58-4ef4-9240-e4d413b2bab4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mantine-3ftbk89k9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mantine-3ftbk89k9']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@placeholder = 'Nhập tên tài khoản của bạn' and @type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Nhập tên tài khoản của bạn&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4fab9d8c-e1ab-414f-a313-24291449a351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập tên tài khoản của bạn</value>
      <webElementGuid>5cd60a74-8ef3-47c0-af34-0a268fc6fd22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mantine-3ftbk89k9</value>
      <webElementGuid>6a212aef-c216-4111-966c-84fc7af07e76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a6e268a2-e066-4f51-90f4-b2a7d8cc1a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9b5001a5-eb66-4db4-9d9a-2318913b82aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-TextInput-defaultVariant mantine-TextInput-input mantine-h9qzwz</value>
      <webElementGuid>9dcf0b35-90c3-4e86-b4b8-3d31ea89464a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-3ftbk89k9&quot;)</value>
      <webElementGuid>214c92a2-c368-4f13-a08a-f9443d253d4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mantine-3ftbk89k9']</value>
      <webElementGuid>50eafaa5-2dc2-46f6-a600-6a43776eb979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div/form/div/div/input</value>
      <webElementGuid>b61bc6e4-a314-4526-accf-e772a2466a07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/input</value>
      <webElementGuid>9ca1f51b-2267-4594-83c4-8639a5f28c22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Nhập tên tài khoản của bạn' and @id = 'mantine-3ftbk89k9' and @type = 'text']</value>
      <webElementGuid>cd5aa550-1c93-409f-8a00-d7612f2a9776</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
