<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Xc nhn t mua_1</name>
   <tag></tag>
   <elementGuidId>4d9c4faa-564b-4cf6-9b59-693b5e4dccd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.mantine-Button-filled.mantine-Button-root.mantine-Group-child.mantine-5q9waz</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[22]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and (text() = 'Xác nhận đặt mua' or . = 'Xác nhận đặt mua')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Xác nhận đặt mua&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c1e92a3b-d267-4176-b935-e329b873b3cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-Button-filled mantine-Button-root mantine-Group-child mantine-5q9waz</value>
      <webElementGuid>96db9efc-752e-4768-8746-62d5fdb33620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9c35d996-d825-4835-a719-676fb6a9f141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Xác nhận đặt mua</value>
      <webElementGuid>e0a5d713-171d-4828-bf05-7aa53b5e78f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-n745x9m7n-body&quot;)/div[@class=&quot;mantine-Group-root mantine-147cgkf&quot;]/button[@class=&quot;mantine-Button-filled mantine-Button-root mantine-Group-child mantine-5q9waz&quot;]</value>
      <webElementGuid>92cb2388-3c44-4949-b5d7-2402c22f73a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[22]</value>
      <webElementGuid>7891ea10-7635-4ff5-b695-e14afc030b18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mantine-n745x9m7n-body']/div[2]/button[2]</value>
      <webElementGuid>9fb9a9cf-805f-4e50-bc84-5858c54be31b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hủy'])[1]/following::button[1]</value>
      <webElementGuid>bd0466af-c4dd-464a-b9c8-d67a35ee7e33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thanh toán PayPal'])[1]/following::button[2]</value>
      <webElementGuid>61c494c3-3705-4edc-be1e-404e0563b9ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client'])[1]/preceding::button[1]</value>
      <webElementGuid>536fade6-649b-4ae2-a98f-521ecbe25a7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[2]</value>
      <webElementGuid>282ba15e-52ae-4da6-9c12-a02e6b196d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Xác nhận đặt mua' or . = 'Xác nhận đặt mua')]</value>
      <webElementGuid>46b3d693-baa2-478c-ad52-cb6df13ed8ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
