<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ng_1</name>
   <tag></tag>
   <elementGuidId>7301ba00-2825-48c2-a47a-19550436ec9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.mantine-Button-default.mantine-Button-root.mantine-1buwzwa</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[21]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and (text() = 'Đóng' or . = 'Đóng')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Đóng&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6c6743c2-eb1a-48bf-b5ec-0990533bec6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-Button-default mantine-Button-root mantine-1buwzwa</value>
      <webElementGuid>f45cc250-4ba2-40d0-8639-04d5f817f2d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6b682442-9e52-4084-9b82-e063a4e9963d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đóng</value>
      <webElementGuid>d262f39a-b071-46f4-8bdd-4a48604be381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-n745x9m7n-body&quot;)/div[@class=&quot;mantine-Stack-root mantine-1ufc0vz&quot;]/div[@class=&quot;mantine-Stack-root mantine-8ylo13&quot;]/button[@class=&quot;mantine-Button-default mantine-Button-root mantine-1buwzwa&quot;]</value>
      <webElementGuid>25139bc8-6f5c-43b4-b03f-bd3fb6677583</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[21]</value>
      <webElementGuid>1e3f50ea-48d3-474a-82ec-d3c91975dd62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mantine-n745x9m7n-body']/div/div/button</value>
      <webElementGuid>1060dcf8-edc3-4a8a-aefe-3c18b7867ef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đã có lỗi xảy ra'])[1]/following::button[1]</value>
      <webElementGuid>942757d7-cad4-430f-b5ef-9fb8139511de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thông báo xác nhận đặt mua'])[1]/following::button[1]</value>
      <webElementGuid>626dfe31-b14a-449a-bad4-b4ab3fd10650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client'])[1]/preceding::button[1]</value>
      <webElementGuid>40c12e80-054c-4f6d-b641-7b0a26385f83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/div/div/button</value>
      <webElementGuid>36bc0ae6-1a2c-48ba-9366-bfa95664a3b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Đóng' or . = 'Đóng')]</value>
      <webElementGuid>69ae2cad-3e86-4246-828a-35fcb456313a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
