<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tin mt_mantine-85pn8f171</name>
   <tag></tag>
   <elementGuidId>59e207da-138d-44db-adf5-d0afebafd6b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mantine-qwilqlikk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mantine-qwilqlikk']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'radio' and @id = 'mantine-qwilqlikk' and @name = 'mantine-85pn8f171']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;PayPal&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>efbcf400-526a-4b17-8c5a-e5754cb098ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-16212yj mantine-RadioGroup-radio</value>
      <webElementGuid>7410650f-4c07-4466-85b0-328b728a7771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>502d2ec3-cb62-4ccb-aaa7-bc32d5c269cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mantine-qwilqlikk</value>
      <webElementGuid>3c09a63b-c44c-42ca-9c74-eff53af326e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mantine-85pn8f171</value>
      <webElementGuid>5a84c3e0-8d62-4f21-8460-55e7689aff3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>PAYPAL</value>
      <webElementGuid>0091a5a0-e221-4296-a81d-d130d8b9314a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-qwilqlikk&quot;)</value>
      <webElementGuid>a9f073b2-1fea-4327-bff0-7a453a8191f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mantine-qwilqlikk']</value>
      <webElementGuid>9e23d98e-1cca-4bac-b58d-13e2d64316ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div[2]/div[2]/div/div[3]/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>09ec7b1c-90db-4d0f-b286-f0715e858be1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>e4fa8b49-3d3d-4010-8f61-fdc939d922ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'mantine-qwilqlikk' and @name = 'mantine-85pn8f171']</value>
      <webElementGuid>92bec744-1a26-4dbf-aac3-af84d8b589e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
