<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Xc nhn t mua</name>
   <tag></tag>
   <elementGuidId>cb92cd81-4821-4ad0-9500-73a45467aebc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.mantine-Button-filled.mantine-Button-root.mantine-Group-child.mantine-5q9waz</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[19]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and (text() = 'Xác nhận đặt mua' or . = 'Xác nhận đặt mua')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Xác nhận đặt mua&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1c9eeb0a-8ead-4fd9-a361-21f2bcddba4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-Button-filled mantine-Button-root mantine-Group-child mantine-5q9waz</value>
      <webElementGuid>f8e3bc5c-8905-4bc0-bdf1-1532a161e9f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b012ef67-c9d0-4c0d-a3de-73782e3816ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Xác nhận đặt mua</value>
      <webElementGuid>9e1fb29d-235d-4886-8c60-06165be8e8f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-fsubtcxzi-body&quot;)/div[@class=&quot;mantine-Group-root mantine-147cgkf&quot;]/button[@class=&quot;mantine-Button-filled mantine-Button-root mantine-Group-child mantine-5q9waz&quot;]</value>
      <webElementGuid>58002729-701a-4ad9-91fd-14b316ed6954</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[19]</value>
      <webElementGuid>0b5a687c-0c90-4f30-925e-920ec7bc872c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mantine-fsubtcxzi-body']/div[2]/button[2]</value>
      <webElementGuid>4857816d-4153-4e23-8ab8-4f50845290b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hủy'])[1]/following::button[1]</value>
      <webElementGuid>b1d3287c-72d2-4e77-a36b-6a7c35b072e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thanh toán tiền mặt'])[1]/following::button[2]</value>
      <webElementGuid>a0e289f8-0b2a-4ec3-a82c-b5a376945a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client'])[1]/preceding::button[1]</value>
      <webElementGuid>706f33df-5912-4abf-8331-22d1baeb1ab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[2]</value>
      <webElementGuid>ccbe7681-78da-4208-a74f-f89ee5e601df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Xác nhận đặt mua' or . = 'Xác nhận đặt mua')]</value>
      <webElementGuid>cfc21706-fff1-4781-822f-26e86c4b0a28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
