<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1</name>
   <tag></tag>
   <elementGuidId>93f461b5-ef75-422e-82b5-60949aedf01e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mantine-Group-root.mantine-1ssvveo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/header/div/div/div/div[2]/div/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;1&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6ac30fd1-0bb3-4be8-9376-45ffaab1a386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-Group-root mantine-1ssvveo</value>
      <webElementGuid>a7e6c133-d293-4b5b-b68e-134028f15d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>54152455-e53a-4877-a4ef-1ee4fcb297f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/header[@class=&quot;mantine-1eubo87&quot;]/div[@class=&quot;mantine-Container-root mantine-10nsg3v&quot;]/div[@class=&quot;mantine-Stack-root mantine-1fod3h5&quot;]/div[@class=&quot;mantine-Group-root mantine-rvtoj&quot;]/div[@class=&quot;mantine-Group-root mantine-Group-child mantine-1cighqm&quot;]/div[@class=&quot;mantine-Tooltip-root mantine-gc2cx1&quot;]/a[@class=&quot;mantine-UnstyledButton-root mantine-14iebtj&quot;]/div[@class=&quot;mantine-Group-root mantine-1ssvveo&quot;]</value>
      <webElementGuid>bc70fe2f-51a2-4e57-9f4b-38286130c9fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/header/div/div/div/div[2]/div/a/div</value>
      <webElementGuid>4c732ad4-6750-47bb-bd99-151d90c6cd61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Danh mục sản phẩm'])[1]/preceding::div[10]</value>
      <webElementGuid>371d65bd-b29e-44f9-8b8f-ddafcb3a0150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sản phẩm mới'])[1]/preceding::div[13]</value>
      <webElementGuid>05b2f99a-3849-409a-8e8c-822ecbe39cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>b73d8750-db18-4535-bb7a-78f5727aa696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '1' or . = '1')]</value>
      <webElementGuid>edeb43c1-0141-491a-8835-c3cf945d7a55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
